/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Models.Beans.BillBean;
import Models.Beans.ElectricReadingBean;
import Models.Beans.RoomBean;
import Models.Beans.WaterReadingBean;
import Models.DAOImplementation.BillDAOImplementation;
import Models.DAOImplementation.ElectricReadingDAOImplementation;
import Models.DAOImplementation.RoomDAOImplementation;
import Models.DAOImplementation.WaterDAOImplementation;
import Models.DAOInterface.BillDAOInterface;
import Models.DAOInterface.ElectricReadingDAOInterface;
import Models.DAOInterface.RoomDAOInterface;
import Models.DAOInterface.WaterReadingDAOInterface;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jao
 */
public class EditBillPricePanel extends javax.swing.JPanel {

    /**
     * Creates new form EditBillPricePanel
     */
    private boolean dot = false;
    private float priceperkw;
    private float pricepercubicmeter;
    private String year;
    private String month;

    public EditBillPricePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jTextField1.setText("jTextField1");
        add(jTextField1);
        jTextField1.setBounds(290, 340, 84, 28);

        jTextField2.setText("jTextField2");
        add(jTextField2);
        jTextField2.setBounds(290, 370, 84, 28);

        jTextField3.setText("jTextField3");
        add(jTextField3);
        jTextField3.setBounds(540, 340, 84, 28);

        jTextField4.setText("jTextField4");
        add(jTextField4);
        jTextField4.setBounds(540, 370, 84, 28);

        jTextField5.setText("jTextField5");
        add(jTextField5);
        jTextField5.setBounds(720, 340, 84, 28);

        jLabel1.setText("JLabel For Month Name");
        add(jLabel1);
        jLabel1.setBounds(210, 240, 160, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/confirm.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(750, 450, 80, 40);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(640, 460, 97, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/editgeneralbills-peg-edited.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1000, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (jTextField1.getText().isEmpty()
                || jTextField2.getText().isEmpty()
                || jTextField3.getText().isEmpty()
                || jTextField4.getText().isEmpty()
                || jTextField5.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input ALL necessary fields.");
        } else {
            String totalelectricityconsumption = jTextField1.getText();
            String totalelectricitycost = jTextField2.getText();

            String totalwaterconsumption = jTextField3.getText();
            String totalwatercost = jTextField4.getText();

            String roomrent = jTextField5.getText();

            //price ng room
            double price = Double.parseDouble(roomrent);

            priceperkw = Float.parseFloat(totalelectricitycost) / Float.parseFloat(totalelectricityconsumption);
            System.out.println("Price per kw: " + priceperkw);

            pricepercubicmeter = Float.parseFloat(totalwatercost) / Float.parseFloat(totalwaterconsumption);
            System.out.println(pricepercubicmeter);

            boolean paidRent = false;
            boolean paidWater = false;
            boolean paidElectric = false;
            boolean addbill = false;
            BillBean bbean = new BillBean();
            BillDAOInterface bdao = new BillDAOImplementation();
            // initialize billbean for each room

            RoomDAOInterface rdao = new RoomDAOImplementation();
            ArrayList<RoomBean> rbeanlist = new ArrayList<RoomBean>();
            rbeanlist = rdao.getAllRooms();
            RoomBean rbean = new RoomBean();

            ElectricReadingBean ebean = new ElectricReadingBean();
            WaterReadingBean wbean = new WaterReadingBean();
            ElectricReadingDAOInterface edao = new ElectricReadingDAOImplementation();
            WaterReadingDAOInterface wdao = new WaterDAOImplementation();

            ArrayList<BillBean> bbeanlist = bdao.getAllBills();
            wbean.setPricepercubicmeter(pricepercubicmeter);
            ebean.setPriceperKW(priceperkw);
            java.sql.Date dateread = ebean.getDateRead();
            wbean.setDateRead(dateread);
            ebean.setDateRead(dateread);
            wbean.setCurrentcubicmeter(0);
            ebean.setCurrentKW(0);
            wbean.setPrice(0);
            ebean.setPrice(0);
            for (int i = 0; i < rbeanlist.size(); i++) {

                bbean = new BillBean();

                bbean.setBill_roomID(rbeanlist.get(i).getRoomID());
                bbean.setPrice(price);
                bbean.setPaidElectric(paidElectric);
                bbean.setPaidWater(paidWater);
                bbean.setPaidRent(paidRent);

                if (bdao.addBill(bbean) == true) {
                    addbill = true;
                } else {
                    addbill = false;
                }
                int billID = 0;
                if (rbeanlist.size() <= bdao.getAllBills().size()) { // mas malaki yung billsize{

                    billID = bdao.getAllBills().size() - (rbeanlist.size());
                    if (billID == 0) {
                        billID = 50;
                    }
                } else { // start pa lang
                    billID = i + 1;
                }

                System.out.println(billID);
                wbean.setWater_billID(billID);
                ebean.setElectric_billID(billID);
                wdao.addWaterReadingToRoom(wbean, billID);
                edao.addElectricReadingToRoom(ebean, billID);
            }

            if (addbill) {
                JOptionPane.showMessageDialog(null, "Succesfully added bills for all rooms!");
            } else {
                JOptionPane.showMessageDialog(null, "Unsuccessful in adding bills.");
            }

        }

        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public void changeAllBill() {
        BillDAOInterface bdao = new BillDAOImplementation();
        ElectricReadingDAOInterface edao = new ElectricReadingDAOImplementation();
        WaterReadingDAOInterface wdao = new WaterDAOImplementation();
        RoomDAOInterface rdao = new RoomDAOImplementation();
        
        ArrayList<RoomBean> rbeanlist = new ArrayList<RoomBean>();
        rbeanlist = rdao.getAllRooms();
        
        ArrayList<BillBean> blist = bdao.getAllBills();
        
        BillBean bbean = new BillBean();
        WaterReadingBean wbean = new WaterReadingBean();
        ElectricReadingBean ebean = new ElectricReadingBean();
        
        float electricprice;
        float waterprice;
        
        for(int i=0; i<rbeanlist.size(); i++) {
            bbean = bdao.getBillsByRoomID(i);
            wbean = wdao.getWaterReadingsByBillID(bbean.getBillID());
            ebean = edao.getElectricReadingByBillID(bbean.getBillID());
            
            if(wbean.getCurrentcubicmeter()==0) {
                
            }
            else {
                waterprice = wbean.getCurrentcubicmeter() * wbean.getPricepercubicmeter();
                wbean.setPrice(waterprice);
                wdao.editWaterReading(wbean, wbean.getWater_billID());
            }
            
            if(ebean.getCurrentKW()==0) {
                
            }
            else {
                electricprice = ebean.getCurrentKW() * ebean.getPriceperKW();
                wbean.setPrice(electricprice);
                edao.editElectricReading(ebean, ebean.getElectric_billID());
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
